### ISSUE TITLE
More Textures for the Game

### ISSUE THREAD

**Issue by Johncrhamilton** [Permafrost-Game/Permafrost#103]
The game is still lacking textures for some core buildings/environment and some of the textures need changes to fit the current style of the game.

- [ ] Campfire needs a texture update.
- [ ] Farm needs a texture update plus a not planted texture.
- [ ] Bush needs a texture update.
- [x] Storage building needs a texture.
- [x] Tower needs a texture.

This is related to #91

**Comment by ajaysharmx** [comment]
Could someone clarify what they mean by texture update?
