### ISSUE TITLE
Create/Find missing textures and assets

### ISSUE THREAD

**Issue by JR-Morgan** [Permafrost-Game/Permafrost#154]
Multiple textures need to be sourced for the game. Either created or found from https://opengameart.org/

It is important that these texutres fit with the current games aesthetic, and are apropreatly sized.
Textures can be any physical dimention and are NOT limited to exponents of 2.
It is important that realtive size is considered.
The size of a bear is 73x50px and a colonist is 32x64px, and a rabbit is 30x32.

A list of textures that we need are as follows:

- [x] Goat
- [x] Farm:
    - [x] Harvested (mostly dirt)
    - [x] Freshly planted (dirt with some seeds
    - [x] Growing (early plant)
    - We have a harvestable farm texture (with wheat grown) see https://github.com/Permafrost-Game/Permafrost/blob/develop/TeamProject/GlobalWarmingGame/Content/textures/interactables/buildings/farm/sprite0.png
- [x] Wolf
- [x] Merchant

**Comment by Johncrhamilton** [comment]
Could we also get a merchant (similar style to colonist, maybe add a hat)
